# Generated by Django 4.1 on 2022-09-02 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_user_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog'),
            preserve_default=False,
        ),
    ]
