# Generated by Django 4.1 on 2022-09-03 10:36

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_blog_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
