# Generated by Django 4.1 on 2022-11-19 10:34

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
    ]
